host:
  service:
    ticket: "ticketService"
    flight: "flightService"
    bonus: "bonusService"

path:
  service:
    ticket: "api/v1/tickets"
    flight: "api/v1/flights"
    bonus: "api/v1/bonuses"

port:
  service:
    ticket: "8050"
    flight: "8060"
    bonus: "8070"
