spring:
  flyway:
    baselineOnMigrate: true
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/bonuses
    username: program
    password: test
